global:
  scrape_interval: 10s

scrape_configs:
  - job_name: server
    static_configs:
      - targets:
#          - docker.for.mac.localhost:5000
#          - docker-tutorial_server_1:5000
          - '192.168.99.124:5000'
